---
- name: Install Docker, K3s, and Jenkins on EC2
  hosts: localhost
  become: true
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update yum package index
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Install prerequisites for Docker (Debian/Ubuntu)
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present
      when: ansible_os_family == "Debian"

    - name: Install prerequisites for Docker (RedHat/CentOS)
      yum:
        name:
          - device-mapper-persistent-data
          - lvm2
          - yum-utils
        state: present
      when: ansible_os_family == "RedHat"

    - name: Add Docker GPG key (Debian/Ubuntu)
      apt_key:
        url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker repository (Debian/Ubuntu)
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Docker repository (RedHat/CentOS)
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      when: ansible_os_family == "RedHat"

    - name: Install Docker (Debian/Ubuntu)
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker (RedHat/CentOS)
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create docker group
      group:
        name: docker
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      ignore_errors: yes

    - name: Download K3s install script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: "0755"

    - name: Install K3s
      command: /tmp/k3s-install.sh
      environment:
        INSTALL_K3S_EXEC: --docker

    - name: Create .kube directory
      file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    - name: Copy kubeconfig
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"

    - name: Install OpenJDK
      package:
        name: openjdk-17-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Install OpenJDK (RedHat/CentOS)
      yum:
        name: java-17-openjdk
        state: present
      when: ansible_os_family == "RedHat"

    - name: Add Jenkins repository key (Debian/Ubuntu)
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Jenkins repository (Debian/Ubuntu)
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present
      when: ansible_os_family == "Debian"

    - name: Add Jenkins repository (RedHat/CentOS)
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
      when: ansible_os_family == "RedHat"

    - name: Import Jenkins GPG key (RedHat/CentOS)
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Jenkins (Debian/Ubuntu)
      apt:
        name: jenkins
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Jenkins (RedHat/CentOS)
      yum:
        name: jenkins
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Add jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Restart Jenkins service
      systemd:
        name: jenkins
        state: restarted

    - name: Get Jenkins initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      ignore_errors: yes

    - name: Display Jenkins initial admin password
      debug:
        msg: "Jenkins initial admin password: {{ jenkins_password.stdout }}"
      when: jenkins_password.rc == 0
